### ISSUE TITLE
lodash not working

### ISSUE THREAD

**Issue by austinkelleher** [charlieduong94/dotfiles#1]
I tried running your `lodash` command from here: https://github.com/charlieduong94/dotfiles/blob/master/.zprofile#L57

My LifeOmic dashboard does not open

```
austin@austin# lodash
zsh: command not found: lifeomic-deployment-dashboard
```

What should I do?

**Comment by andrejewski** [comment]
You have to do `npm install --global lodash` and then it will work.

**Comment by charlieduong94** [comment]
Thanks for opening this issue @austinkelleher. @andrejewski is correct. Just install `lodash` and everything will #JustWork.
